// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/knoci/roaming-world/audiobook/internal/biz"
	"github.com/knoci/roaming-world/audiobook/internal/conf"
	"github.com/knoci/roaming-world/audiobook/internal/data"
	"github.com/knoci/roaming-world/audiobook/internal/server"
	"github.com/knoci/roaming-world/audiobook/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	audiobookRepo := data.NewAudiobookRepo(dataData, logger)
	audiobookUsecase := biz.NewAudiobookUsecase(audiobookRepo, logger)
	audiobookService := service.NewAudiobookService(audiobookUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, audiobookService, logger)
	httpServer := server.NewHTTPServer(confServer, audiobookService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
