// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/knoci/roaming-world/food/internal/biz"
	"github.com/knoci/roaming-world/food/internal/conf"
	"github.com/knoci/roaming-world/food/internal/data"
	"github.com/knoci/roaming-world/food/internal/server"
	"github.com/knoci/roaming-world/food/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	foodRepo := data.NewFoodRepo(dataData, logger)
	foodUsecase := biz.NewFoodUsecase(foodRepo, logger)
	foodService := service.NewFoodService(foodUsecase)
	grpcServer := server.NewGRPCServer(confServer, foodService, logger)
	httpServer := server.NewHTTPServer(confServer, foodService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
