// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/comment/v1/comment.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CommentMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CommentMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommentMessageMultiError,
// or nil if none found.
func (m *CommentMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Cid

	// no validation rules for Target

	// no validation rules for Content

	// no validation rules for Likes

	// no validation rules for Uid

	// no validation rules for Name

	// no validation rules for Avatar

	// no validation rules for Replycid

	// no validation rules for Replyname

	// no validation rules for Time

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return CommentMessageMultiError(errors)
	}

	return nil
}

// CommentMessageMultiError is an error wrapping multiple validation errors
// returned by CommentMessage.ValidateAll() if the designated constraints
// aren't met.
type CommentMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentMessageMultiError) AllErrors() []error { return m }

// CommentMessageValidationError is the validation error returned by
// CommentMessage.Validate if the designated constraints aren't met.
type CommentMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentMessageValidationError) ErrorName() string { return "CommentMessageValidationError" }

// Error satisfies the builtin error interface
func (e CommentMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentMessageValidationError{}

// Validate checks the field values on CreateCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCommentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCommentRequestMultiError, or nil if none found.
func (m *CreateCommentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCommentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTarget()) < 1 {
		err := CreateCommentRequestValidationError{
			field:  "Target",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetContent()) < 1 {
		err := CreateCommentRequestValidationError{
			field:  "Content",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Replycid

	// no validation rules for Replyname

	if len(errors) > 0 {
		return CreateCommentRequestMultiError(errors)
	}

	return nil
}

// CreateCommentRequestMultiError is an error wrapping multiple validation
// errors returned by CreateCommentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateCommentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCommentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCommentRequestMultiError) AllErrors() []error { return m }

// CreateCommentRequestValidationError is the validation error returned by
// CreateCommentRequest.Validate if the designated constraints aren't met.
type CreateCommentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentRequestValidationError) ErrorName() string {
	return "CreateCommentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCommentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentRequestValidationError{}

// Validate checks the field values on CreateCommentReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCommentReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCommentReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCommentReplyMultiError, or nil if none found.
func (m *CreateCommentReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCommentReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetComment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateCommentReplyValidationError{
					field:  "Comment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateCommentReplyValidationError{
					field:  "Comment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetComment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateCommentReplyValidationError{
				field:  "Comment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateCommentReplyMultiError(errors)
	}

	return nil
}

// CreateCommentReplyMultiError is an error wrapping multiple validation errors
// returned by CreateCommentReply.ValidateAll() if the designated constraints
// aren't met.
type CreateCommentReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCommentReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCommentReplyMultiError) AllErrors() []error { return m }

// CreateCommentReplyValidationError is the validation error returned by
// CreateCommentReply.Validate if the designated constraints aren't met.
type CreateCommentReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCommentReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCommentReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCommentReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCommentReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCommentReplyValidationError) ErrorName() string {
	return "CreateCommentReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCommentReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCommentReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCommentReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCommentReplyValidationError{}

// Validate checks the field values on DeleteCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCommentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCommentRequestMultiError, or nil if none found.
func (m *DeleteCommentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCommentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCid()) < 1 {
		err := DeleteCommentRequestValidationError{
			field:  "Cid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteCommentRequestMultiError(errors)
	}

	return nil
}

// DeleteCommentRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteCommentRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteCommentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCommentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCommentRequestMultiError) AllErrors() []error { return m }

// DeleteCommentRequestValidationError is the validation error returned by
// DeleteCommentRequest.Validate if the designated constraints aren't met.
type DeleteCommentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCommentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCommentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCommentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCommentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCommentRequestValidationError) ErrorName() string {
	return "DeleteCommentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCommentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCommentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCommentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCommentRequestValidationError{}

// Validate checks the field values on DeleteCommentReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCommentReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCommentReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCommentReplyMultiError, or nil if none found.
func (m *DeleteCommentReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCommentReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return DeleteCommentReplyMultiError(errors)
	}

	return nil
}

// DeleteCommentReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteCommentReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteCommentReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCommentReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCommentReplyMultiError) AllErrors() []error { return m }

// DeleteCommentReplyValidationError is the validation error returned by
// DeleteCommentReply.Validate if the designated constraints aren't met.
type DeleteCommentReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCommentReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCommentReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCommentReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCommentReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCommentReplyValidationError) ErrorName() string {
	return "DeleteCommentReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCommentReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCommentReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCommentReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCommentReplyValidationError{}

// Validate checks the field values on LikeCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LikeCommentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LikeCommentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LikeCommentRequestMultiError, or nil if none found.
func (m *LikeCommentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LikeCommentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCid()) < 1 {
		err := LikeCommentRequestValidationError{
			field:  "Cid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LikeCommentRequestMultiError(errors)
	}

	return nil
}

// LikeCommentRequestMultiError is an error wrapping multiple validation errors
// returned by LikeCommentRequest.ValidateAll() if the designated constraints
// aren't met.
type LikeCommentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LikeCommentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LikeCommentRequestMultiError) AllErrors() []error { return m }

// LikeCommentRequestValidationError is the validation error returned by
// LikeCommentRequest.Validate if the designated constraints aren't met.
type LikeCommentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LikeCommentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LikeCommentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LikeCommentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LikeCommentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LikeCommentRequestValidationError) ErrorName() string {
	return "LikeCommentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e LikeCommentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLikeCommentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LikeCommentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LikeCommentRequestValidationError{}

// Validate checks the field values on LikeCommentReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LikeCommentReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LikeCommentReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LikeCommentReplyMultiError, or nil if none found.
func (m *LikeCommentReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LikeCommentReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return LikeCommentReplyMultiError(errors)
	}

	return nil
}

// LikeCommentReplyMultiError is an error wrapping multiple validation errors
// returned by LikeCommentReply.ValidateAll() if the designated constraints
// aren't met.
type LikeCommentReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LikeCommentReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LikeCommentReplyMultiError) AllErrors() []error { return m }

// LikeCommentReplyValidationError is the validation error returned by
// LikeCommentReply.Validate if the designated constraints aren't met.
type LikeCommentReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LikeCommentReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LikeCommentReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LikeCommentReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LikeCommentReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LikeCommentReplyValidationError) ErrorName() string { return "LikeCommentReplyValidationError" }

// Error satisfies the builtin error interface
func (e LikeCommentReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLikeCommentReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LikeCommentReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LikeCommentReplyValidationError{}

// Validate checks the field values on GetCommentListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCommentListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommentListRequestMultiError, or nil if none found.
func (m *GetCommentListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAid()) < 1 {
		err := GetCommentListRequestValidationError{
			field:  "Aid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCommentListRequestMultiError(errors)
	}

	return nil
}

// GetCommentListRequestMultiError is an error wrapping multiple validation
// errors returned by GetCommentListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCommentListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentListRequestMultiError) AllErrors() []error { return m }

// GetCommentListRequestValidationError is the validation error returned by
// GetCommentListRequest.Validate if the designated constraints aren't met.
type GetCommentListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentListRequestValidationError) ErrorName() string {
	return "GetCommentListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentListRequestValidationError{}

// Validate checks the field values on GetCommentListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCommentListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommentListReplyMultiError, or nil if none found.
func (m *GetCommentListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCommentListReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCommentListReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCommentListReplyValidationError{
					field:  fmt.Sprintf("Comments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetCommentListReplyMultiError(errors)
	}

	return nil
}

// GetCommentListReplyMultiError is an error wrapping multiple validation
// errors returned by GetCommentListReply.ValidateAll() if the designated
// constraints aren't met.
type GetCommentListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentListReplyMultiError) AllErrors() []error { return m }

// GetCommentListReplyValidationError is the validation error returned by
// GetCommentListReply.Validate if the designated constraints aren't met.
type GetCommentListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentListReplyValidationError) ErrorName() string {
	return "GetCommentListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentListReplyValidationError{}

// Validate checks the field values on GetCommentListWithRepliesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetCommentListWithRepliesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentListWithRepliesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetCommentListWithRepliesRequestMultiError, or nil if none found.
func (m *GetCommentListWithRepliesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentListWithRepliesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAid()) < 1 {
		err := GetCommentListWithRepliesRequestValidationError{
			field:  "Aid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCommentListWithRepliesRequestMultiError(errors)
	}

	return nil
}

// GetCommentListWithRepliesRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetCommentListWithRepliesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCommentListWithRepliesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentListWithRepliesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentListWithRepliesRequestMultiError) AllErrors() []error { return m }

// GetCommentListWithRepliesRequestValidationError is the validation error
// returned by GetCommentListWithRepliesRequest.Validate if the designated
// constraints aren't met.
type GetCommentListWithRepliesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentListWithRepliesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentListWithRepliesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentListWithRepliesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentListWithRepliesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentListWithRepliesRequestValidationError) ErrorName() string {
	return "GetCommentListWithRepliesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentListWithRepliesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentListWithRepliesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentListWithRepliesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentListWithRepliesRequestValidationError{}

// Validate checks the field values on GetCommentListWithRepliesReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCommentListWithRepliesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentListWithRepliesReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetCommentListWithRepliesReplyMultiError, or nil if none found.
func (m *GetCommentListWithRepliesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentListWithRepliesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCommentListWithRepliesReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCommentListWithRepliesReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCommentListWithRepliesReplyValidationError{
					field:  fmt.Sprintf("Comments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetCommentListWithRepliesReplyMultiError(errors)
	}

	return nil
}

// GetCommentListWithRepliesReplyMultiError is an error wrapping multiple
// validation errors returned by GetCommentListWithRepliesReply.ValidateAll()
// if the designated constraints aren't met.
type GetCommentListWithRepliesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentListWithRepliesReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentListWithRepliesReplyMultiError) AllErrors() []error { return m }

// GetCommentListWithRepliesReplyValidationError is the validation error
// returned by GetCommentListWithRepliesReply.Validate if the designated
// constraints aren't met.
type GetCommentListWithRepliesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentListWithRepliesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentListWithRepliesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentListWithRepliesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentListWithRepliesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentListWithRepliesReplyValidationError) ErrorName() string {
	return "GetCommentListWithRepliesReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentListWithRepliesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentListWithRepliesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentListWithRepliesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentListWithRepliesReplyValidationError{}

// Validate checks the field values on GetReplyListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetReplyListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReplyListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReplyListRequestMultiError, or nil if none found.
func (m *GetReplyListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReplyListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCid()) < 1 {
		err := GetReplyListRequestValidationError{
			field:  "Cid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetReplyListRequestMultiError(errors)
	}

	return nil
}

// GetReplyListRequestMultiError is an error wrapping multiple validation
// errors returned by GetReplyListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetReplyListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReplyListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReplyListRequestMultiError) AllErrors() []error { return m }

// GetReplyListRequestValidationError is the validation error returned by
// GetReplyListRequest.Validate if the designated constraints aren't met.
type GetReplyListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReplyListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReplyListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReplyListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReplyListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReplyListRequestValidationError) ErrorName() string {
	return "GetReplyListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetReplyListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReplyListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReplyListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReplyListRequestValidationError{}

// Validate checks the field values on GetReplyListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetReplyListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReplyListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReplyListReplyMultiError, or nil if none found.
func (m *GetReplyListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReplyListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetReplyListReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetReplyListReplyValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetReplyListReplyValidationError{
					field:  fmt.Sprintf("Comments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetReplyListReplyMultiError(errors)
	}

	return nil
}

// GetReplyListReplyMultiError is an error wrapping multiple validation errors
// returned by GetReplyListReply.ValidateAll() if the designated constraints
// aren't met.
type GetReplyListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReplyListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReplyListReplyMultiError) AllErrors() []error { return m }

// GetReplyListReplyValidationError is the validation error returned by
// GetReplyListReply.Validate if the designated constraints aren't met.
type GetReplyListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReplyListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReplyListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReplyListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReplyListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReplyListReplyValidationError) ErrorName() string {
	return "GetReplyListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetReplyListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReplyListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReplyListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReplyListReplyValidationError{}
