// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/comment/v1/comment.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommentMessage 评论信息
type CommentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Likes         int32                  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	Uid           string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Replycid      string                 `protobuf:"bytes,8,opt,name=replycid,proto3" json:"replycid,omitempty"`
	Replyname     string                 `protobuf:"bytes,9,opt,name=replyname,proto3" json:"replyname,omitempty"`
	Time          string                 `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentMessage) Reset() {
	*x = CommentMessage{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentMessage) ProtoMessage() {}

func (x *CommentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentMessage.ProtoReflect.Descriptor instead.
func (*CommentMessage) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *CommentMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CommentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentMessage) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *CommentMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CommentMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommentMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CommentMessage) GetReplycid() string {
	if x != nil {
		return x.Replycid
	}
	return ""
}

func (x *CommentMessage) GetReplyname() string {
	if x != nil {
		return x.Replyname
	}
	return ""
}

func (x *CommentMessage) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *CommentMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateCommentRequest 创建评论请求
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`       // 文章AID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`     // 评论内容
	Replycid      string                 `protobuf:"bytes,3,opt,name=replycid,proto3" json:"replycid,omitempty"`   // 回复的评论CID
	Replyname     string                 `protobuf:"bytes,4,opt,name=replyname,proto3" json:"replyname,omitempty"` // 回复的用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetReplycid() string {
	if x != nil {
		return x.Replycid
	}
	return ""
}

func (x *CreateCommentRequest) GetReplyname() string {
	if x != nil {
		return x.Replyname
	}
	return ""
}

// CreateCommentReply 创建评论响应
type CreateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentMessage        `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply) Reset() {
	*x = CreateCommentReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply) ProtoMessage() {}

func (x *CreateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply.ProtoReflect.Descriptor instead.
func (*CreateCommentReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentReply) GetComment() *CommentMessage {
	if x != nil {
		return x.Comment
	}
	return nil
}

// DeleteCommentRequest 删除评论请求
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCommentRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// DeleteCommentReply 删除评论响应
type DeleteCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply) Reset() {
	*x = DeleteCommentReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply) ProtoMessage() {}

func (x *DeleteCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// LikeCommentRequest 点赞评论请求
type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *LikeCommentRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// LikeCommentReply 点赞评论响应
type LikeCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReply) Reset() {
	*x = LikeCommentReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReply) ProtoMessage() {}

func (x *LikeCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReply.ProtoReflect.Descriptor instead.
func (*LikeCommentReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *LikeCommentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetCommentListRequest 获取一级评论列表请求
type GetCommentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListRequest) Reset() {
	*x = GetCommentListRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListRequest) ProtoMessage() {}

func (x *GetCommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListRequest.ProtoReflect.Descriptor instead.
func (*GetCommentListRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentListRequest) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

// GetCommentListReply 获取一级评论列表响应
type GetCommentListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentMessage      `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListReply) Reset() {
	*x = GetCommentListReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListReply) ProtoMessage() {}

func (x *GetCommentListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListReply.ProtoReflect.Descriptor instead.
func (*GetCommentListReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommentListReply) GetComments() []*CommentMessage {
	if x != nil {
		return x.Comments
	}
	return nil
}

// GetCommentListWithRepliesRequest 获取一级评论列表及其前两条二级评论请求
type GetCommentListWithRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListWithRepliesRequest) Reset() {
	*x = GetCommentListWithRepliesRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListWithRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListWithRepliesRequest) ProtoMessage() {}

func (x *GetCommentListWithRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListWithRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetCommentListWithRepliesRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentListWithRepliesRequest) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

// GetCommentListWithRepliesReply 获取一级评论列表及其前两条二级评论响应
type GetCommentListWithRepliesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentMessage      `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListWithRepliesReply) Reset() {
	*x = GetCommentListWithRepliesReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListWithRepliesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListWithRepliesReply) ProtoMessage() {}

func (x *GetCommentListWithRepliesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListWithRepliesReply.ProtoReflect.Descriptor instead.
func (*GetCommentListWithRepliesReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentListWithRepliesReply) GetComments() []*CommentMessage {
	if x != nil {
		return x.Comments
	}
	return nil
}

// GetReplyListRequest 获取二级评论列表请求
type GetReplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplyListRequest) Reset() {
	*x = GetReplyListRequest{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyListRequest) ProtoMessage() {}

func (x *GetReplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyListRequest.ProtoReflect.Descriptor instead.
func (*GetReplyListRequest) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *GetReplyListRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// GetReplyListReply 获取二级评论列表响应
type GetReplyListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentMessage      `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplyListReply) Reset() {
	*x = GetReplyListReply{}
	mi := &file_api_comment_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplyListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyListReply) ProtoMessage() {}

func (x *GetReplyListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comment_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyListReply.ProtoReflect.Descriptor instead.
func (*GetReplyListReply) Descriptor() ([]byte, []int) {
	return file_api_comment_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *GetReplyListReply) GetComments() []*CommentMessage {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_api_comment_v1_comment_proto protoreflect.FileDescriptor

const file_api_comment_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/comment/v1/comment.proto\x12\n" +
	"comment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb4\x02\n" +
	"\x0eCommentMessage\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05likes\x18\x04 \x01(\x05R\x05likes\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x1a\n" +
	"\breplycid\x18\b \x01(\tR\breplycid\x12\x1c\n" +
	"\treplyname\x18\t \x01(\tR\treplyname\x12\x12\n" +
	"\x04time\x18\n" +
	" \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x94\x01\n" +
	"\x14CreateCommentRequest\x12\x1f\n" +
	"\x06target\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06target\x12!\n" +
	"\acontent\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontent\x12\x1a\n" +
	"\breplycid\x18\x03 \x01(\tR\breplycid\x12\x1c\n" +
	"\treplyname\x18\x04 \x01(\tR\treplyname\"J\n" +
	"\x12CreateCommentReply\x124\n" +
	"\acomment\x18\x01 \x01(\v2\x1a.comment.v1.CommentMessageR\acomment\"1\n" +
	"\x14DeleteCommentRequest\x12\x19\n" +
	"\x03cid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03cid\",\n" +
	"\x12DeleteCommentReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"/\n" +
	"\x12LikeCommentRequest\x12\x19\n" +
	"\x03cid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03cid\"*\n" +
	"\x10LikeCommentReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"2\n" +
	"\x15GetCommentListRequest\x12\x19\n" +
	"\x03aid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03aid\"M\n" +
	"\x13GetCommentListReply\x126\n" +
	"\bcomments\x18\x01 \x03(\v2\x1a.comment.v1.CommentMessageR\bcomments\"=\n" +
	" GetCommentListWithRepliesRequest\x12\x19\n" +
	"\x03aid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03aid\"X\n" +
	"\x1eGetCommentListWithRepliesReply\x126\n" +
	"\bcomments\x18\x01 \x03(\v2\x1a.comment.v1.CommentMessageR\bcomments\"0\n" +
	"\x13GetReplyListRequest\x12\x19\n" +
	"\x03cid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03cid\"K\n" +
	"\x11GetReplyListReply\x126\n" +
	"\bcomments\x18\x01 \x03(\v2\x1a.comment.v1.CommentMessageR\bcomments2\xbd\x05\n" +
	"\aComment\x12i\n" +
	"\rCreateComment\x12 .comment.v1.CreateCommentRequest\x1a\x1e.comment.v1.CreateCommentReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/comment\x12f\n" +
	"\rDeleteComment\x12 .comment.v1.DeleteCommentRequest\x1a\x1e.comment.v1.DeleteCommentReply\"\x13\x82\xd3\xe4\x93\x02\r*\v/v1/comment\x12h\n" +
	"\vLikeComment\x12\x1e.comment.v1.LikeCommentRequest\x1a\x1c.comment.v1.LikeCommentReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/comment/like\x12n\n" +
	"\x0eGetCommentList\x12!.comment.v1.GetCommentListRequest\x1a\x1f.comment.v1.GetCommentListReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/comment/list\x12\x97\x01\n" +
	"\x19GetCommentListWithReplies\x12,.comment.v1.GetCommentListWithRepliesRequest\x1a*.comment.v1.GetCommentListWithRepliesReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/comment/list/replies\x12k\n" +
	"\fGetReplyList\x12\x1f.comment.v1.GetReplyListRequest\x1a\x1d.comment.v1.GetReplyListReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/comment/repliesB\x1bZ\x19comment/api/comment/v1;v1b\x06proto3"

var (
	file_api_comment_v1_comment_proto_rawDescOnce sync.Once
	file_api_comment_v1_comment_proto_rawDescData []byte
)

func file_api_comment_v1_comment_proto_rawDescGZIP() []byte {
	file_api_comment_v1_comment_proto_rawDescOnce.Do(func() {
		file_api_comment_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_comment_v1_comment_proto_rawDesc), len(file_api_comment_v1_comment_proto_rawDesc)))
	})
	return file_api_comment_v1_comment_proto_rawDescData
}

var file_api_comment_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_comment_v1_comment_proto_goTypes = []any{
	(*CommentMessage)(nil),                   // 0: comment.v1.CommentMessage
	(*CreateCommentRequest)(nil),             // 1: comment.v1.CreateCommentRequest
	(*CreateCommentReply)(nil),               // 2: comment.v1.CreateCommentReply
	(*DeleteCommentRequest)(nil),             // 3: comment.v1.DeleteCommentRequest
	(*DeleteCommentReply)(nil),               // 4: comment.v1.DeleteCommentReply
	(*LikeCommentRequest)(nil),               // 5: comment.v1.LikeCommentRequest
	(*LikeCommentReply)(nil),                 // 6: comment.v1.LikeCommentReply
	(*GetCommentListRequest)(nil),            // 7: comment.v1.GetCommentListRequest
	(*GetCommentListReply)(nil),              // 8: comment.v1.GetCommentListReply
	(*GetCommentListWithRepliesRequest)(nil), // 9: comment.v1.GetCommentListWithRepliesRequest
	(*GetCommentListWithRepliesReply)(nil),   // 10: comment.v1.GetCommentListWithRepliesReply
	(*GetReplyListRequest)(nil),              // 11: comment.v1.GetReplyListRequest
	(*GetReplyListReply)(nil),                // 12: comment.v1.GetReplyListReply
}
var file_api_comment_v1_comment_proto_depIdxs = []int32{
	0,  // 0: comment.v1.CreateCommentReply.comment:type_name -> comment.v1.CommentMessage
	0,  // 1: comment.v1.GetCommentListReply.comments:type_name -> comment.v1.CommentMessage
	0,  // 2: comment.v1.GetCommentListWithRepliesReply.comments:type_name -> comment.v1.CommentMessage
	0,  // 3: comment.v1.GetReplyListReply.comments:type_name -> comment.v1.CommentMessage
	1,  // 4: comment.v1.Comment.CreateComment:input_type -> comment.v1.CreateCommentRequest
	3,  // 5: comment.v1.Comment.DeleteComment:input_type -> comment.v1.DeleteCommentRequest
	5,  // 6: comment.v1.Comment.LikeComment:input_type -> comment.v1.LikeCommentRequest
	7,  // 7: comment.v1.Comment.GetCommentList:input_type -> comment.v1.GetCommentListRequest
	9,  // 8: comment.v1.Comment.GetCommentListWithReplies:input_type -> comment.v1.GetCommentListWithRepliesRequest
	11, // 9: comment.v1.Comment.GetReplyList:input_type -> comment.v1.GetReplyListRequest
	2,  // 10: comment.v1.Comment.CreateComment:output_type -> comment.v1.CreateCommentReply
	4,  // 11: comment.v1.Comment.DeleteComment:output_type -> comment.v1.DeleteCommentReply
	6,  // 12: comment.v1.Comment.LikeComment:output_type -> comment.v1.LikeCommentReply
	8,  // 13: comment.v1.Comment.GetCommentList:output_type -> comment.v1.GetCommentListReply
	10, // 14: comment.v1.Comment.GetCommentListWithReplies:output_type -> comment.v1.GetCommentListWithRepliesReply
	12, // 15: comment.v1.Comment.GetReplyList:output_type -> comment.v1.GetReplyListReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_comment_v1_comment_proto_init() }
func file_api_comment_v1_comment_proto_init() {
	if File_api_comment_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_comment_v1_comment_proto_rawDesc), len(file_api_comment_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_comment_v1_comment_proto_goTypes,
		DependencyIndexes: file_api_comment_v1_comment_proto_depIdxs,
		MessageInfos:      file_api_comment_v1_comment_proto_msgTypes,
	}.Build()
	File_api_comment_v1_comment_proto = out.File
	file_api_comment_v1_comment_proto_goTypes = nil
	file_api_comment_v1_comment_proto_depIdxs = nil
}
