// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/food/v1/food.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FoodMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FoodMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FoodMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FoodMessageMultiError, or
// nil if none found.
func (m *FoodMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *FoodMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Fid

	// no validation rules for Name

	// no validation rules for Describe

	// no validation rules for Recipe

	// no validation rules for Article

	// no validation rules for Location

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return FoodMessageMultiError(errors)
	}

	return nil
}

// FoodMessageMultiError is an error wrapping multiple validation errors
// returned by FoodMessage.ValidateAll() if the designated constraints aren't met.
type FoodMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FoodMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FoodMessageMultiError) AllErrors() []error { return m }

// FoodMessageValidationError is the validation error returned by
// FoodMessage.Validate if the designated constraints aren't met.
type FoodMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FoodMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FoodMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FoodMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FoodMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FoodMessageValidationError) ErrorName() string { return "FoodMessageValidationError" }

// Error satisfies the builtin error interface
func (e FoodMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFoodMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FoodMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FoodMessageValidationError{}

// Validate checks the field values on CreateFoodRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateFoodRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateFoodRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateFoodRequestMultiError, or nil if none found.
func (m *CreateFoodRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateFoodRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 50 {
		err := CreateFoodRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := len(m.GetView()); l < 1 || l > 10 {
		err := CreateFoodRequestValidationError{
			field:  "View",
			reason: "value must contain between 1 and 10 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescribe()) < 1 {
		err := CreateFoodRequestValidationError{
			field:  "Describe",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRecipe()) < 1 {
		err := CreateFoodRequestValidationError{
			field:  "Recipe",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetArticle()) < 1 {
		err := CreateFoodRequestValidationError{
			field:  "Article",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetLocation()); l < 1 || l > 30 {
		err := CreateFoodRequestValidationError{
			field:  "Location",
			reason: "value length must be between 1 and 30 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateFoodRequestMultiError(errors)
	}

	return nil
}

// CreateFoodRequestMultiError is an error wrapping multiple validation errors
// returned by CreateFoodRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateFoodRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateFoodRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateFoodRequestMultiError) AllErrors() []error { return m }

// CreateFoodRequestValidationError is the validation error returned by
// CreateFoodRequest.Validate if the designated constraints aren't met.
type CreateFoodRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateFoodRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateFoodRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateFoodRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateFoodRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateFoodRequestValidationError) ErrorName() string {
	return "CreateFoodRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateFoodRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateFoodRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateFoodRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateFoodRequestValidationError{}

// Validate checks the field values on CreateFoodReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateFoodReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateFoodReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateFoodReplyMultiError, or nil if none found.
func (m *CreateFoodReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateFoodReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFood()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateFoodReplyValidationError{
					field:  "Food",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateFoodReplyValidationError{
					field:  "Food",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFood()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateFoodReplyValidationError{
				field:  "Food",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateFoodReplyMultiError(errors)
	}

	return nil
}

// CreateFoodReplyMultiError is an error wrapping multiple validation errors
// returned by CreateFoodReply.ValidateAll() if the designated constraints
// aren't met.
type CreateFoodReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateFoodReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateFoodReplyMultiError) AllErrors() []error { return m }

// CreateFoodReplyValidationError is the validation error returned by
// CreateFoodReply.Validate if the designated constraints aren't met.
type CreateFoodReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateFoodReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateFoodReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateFoodReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateFoodReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateFoodReplyValidationError) ErrorName() string { return "CreateFoodReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateFoodReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateFoodReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateFoodReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateFoodReplyValidationError{}

// Validate checks the field values on GetFoodListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFoodListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFoodListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFoodListRequestMultiError, or nil if none found.
func (m *GetFoodListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFoodListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetFoodListRequestMultiError(errors)
	}

	return nil
}

// GetFoodListRequestMultiError is an error wrapping multiple validation errors
// returned by GetFoodListRequest.ValidateAll() if the designated constraints
// aren't met.
type GetFoodListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFoodListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFoodListRequestMultiError) AllErrors() []error { return m }

// GetFoodListRequestValidationError is the validation error returned by
// GetFoodListRequest.Validate if the designated constraints aren't met.
type GetFoodListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFoodListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFoodListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFoodListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFoodListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFoodListRequestValidationError) ErrorName() string {
	return "GetFoodListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFoodListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFoodListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFoodListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFoodListRequestValidationError{}

// Validate checks the field values on GetFoodListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetFoodListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFoodListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFoodListReplyMultiError, or nil if none found.
func (m *GetFoodListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFoodListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFoods() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetFoodListReplyValidationError{
						field:  fmt.Sprintf("Foods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetFoodListReplyValidationError{
						field:  fmt.Sprintf("Foods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetFoodListReplyValidationError{
					field:  fmt.Sprintf("Foods[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetFoodListReplyMultiError(errors)
	}

	return nil
}

// GetFoodListReplyMultiError is an error wrapping multiple validation errors
// returned by GetFoodListReply.ValidateAll() if the designated constraints
// aren't met.
type GetFoodListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFoodListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFoodListReplyMultiError) AllErrors() []error { return m }

// GetFoodListReplyValidationError is the validation error returned by
// GetFoodListReply.Validate if the designated constraints aren't met.
type GetFoodListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFoodListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFoodListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFoodListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFoodListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFoodListReplyValidationError) ErrorName() string { return "GetFoodListReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetFoodListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFoodListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFoodListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFoodListReplyValidationError{}

// Validate checks the field values on GetRandomFoodRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRandomFoodRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRandomFoodRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRandomFoodRequestMultiError, or nil if none found.
func (m *GetRandomFoodRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRandomFoodRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetRandomFoodRequestMultiError(errors)
	}

	return nil
}

// GetRandomFoodRequestMultiError is an error wrapping multiple validation
// errors returned by GetRandomFoodRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRandomFoodRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRandomFoodRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRandomFoodRequestMultiError) AllErrors() []error { return m }

// GetRandomFoodRequestValidationError is the validation error returned by
// GetRandomFoodRequest.Validate if the designated constraints aren't met.
type GetRandomFoodRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRandomFoodRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRandomFoodRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRandomFoodRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRandomFoodRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRandomFoodRequestValidationError) ErrorName() string {
	return "GetRandomFoodRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRandomFoodRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRandomFoodRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRandomFoodRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRandomFoodRequestValidationError{}

// Validate checks the field values on GetRandomFoodReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRandomFoodReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRandomFoodReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRandomFoodReplyMultiError, or nil if none found.
func (m *GetRandomFoodReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRandomFoodReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFood()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRandomFoodReplyValidationError{
					field:  "Food",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRandomFoodReplyValidationError{
					field:  "Food",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFood()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRandomFoodReplyValidationError{
				field:  "Food",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRandomFoodReplyMultiError(errors)
	}

	return nil
}

// GetRandomFoodReplyMultiError is an error wrapping multiple validation errors
// returned by GetRandomFoodReply.ValidateAll() if the designated constraints
// aren't met.
type GetRandomFoodReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRandomFoodReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRandomFoodReplyMultiError) AllErrors() []error { return m }

// GetRandomFoodReplyValidationError is the validation error returned by
// GetRandomFoodReply.Validate if the designated constraints aren't met.
type GetRandomFoodReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRandomFoodReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRandomFoodReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRandomFoodReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRandomFoodReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRandomFoodReplyValidationError) ErrorName() string {
	return "GetRandomFoodReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetRandomFoodReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRandomFoodReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRandomFoodReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRandomFoodReplyValidationError{}
