// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/food/v1/food.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Food_CreateFood_FullMethodName    = "/food.v1.Food/CreateFood"
	Food_GetFoodList_FullMethodName   = "/food.v1.Food/GetFoodList"
	Food_GetRandomFood_FullMethodName = "/food.v1.Food/GetRandomFood"
)

// FoodClient is the client API for Food service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FoodService 服务定义
type FoodClient interface {
	// CreateFood 创建食物
	CreateFood(ctx context.Context, in *CreateFoodRequest, opts ...grpc.CallOption) (*CreateFoodReply, error)
	// GetFoodList 获取食物列表
	GetFoodList(ctx context.Context, in *GetFoodListRequest, opts ...grpc.CallOption) (*GetFoodListReply, error)
	// GetRandomFood 获取随机食物
	GetRandomFood(ctx context.Context, in *GetRandomFoodRequest, opts ...grpc.CallOption) (*GetRandomFoodReply, error)
}

type foodClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodClient(cc grpc.ClientConnInterface) FoodClient {
	return &foodClient{cc}
}

func (c *foodClient) CreateFood(ctx context.Context, in *CreateFoodRequest, opts ...grpc.CallOption) (*CreateFoodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFoodReply)
	err := c.cc.Invoke(ctx, Food_CreateFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodClient) GetFoodList(ctx context.Context, in *GetFoodListRequest, opts ...grpc.CallOption) (*GetFoodListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFoodListReply)
	err := c.cc.Invoke(ctx, Food_GetFoodList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodClient) GetRandomFood(ctx context.Context, in *GetRandomFoodRequest, opts ...grpc.CallOption) (*GetRandomFoodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomFoodReply)
	err := c.cc.Invoke(ctx, Food_GetRandomFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServer is the server API for Food service.
// All implementations must embed UnimplementedFoodServer
// for forward compatibility.
//
// FoodService 服务定义
type FoodServer interface {
	// CreateFood 创建食物
	CreateFood(context.Context, *CreateFoodRequest) (*CreateFoodReply, error)
	// GetFoodList 获取食物列表
	GetFoodList(context.Context, *GetFoodListRequest) (*GetFoodListReply, error)
	// GetRandomFood 获取随机食物
	GetRandomFood(context.Context, *GetRandomFoodRequest) (*GetRandomFoodReply, error)
	mustEmbedUnimplementedFoodServer()
}

// UnimplementedFoodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodServer struct{}

func (UnimplementedFoodServer) CreateFood(context.Context, *CreateFoodRequest) (*CreateFoodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFood not implemented")
}
func (UnimplementedFoodServer) GetFoodList(context.Context, *GetFoodListRequest) (*GetFoodListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoodList not implemented")
}
func (UnimplementedFoodServer) GetRandomFood(context.Context, *GetRandomFoodRequest) (*GetRandomFoodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomFood not implemented")
}
func (UnimplementedFoodServer) mustEmbedUnimplementedFoodServer() {}
func (UnimplementedFoodServer) testEmbeddedByValue()              {}

// UnsafeFoodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServer will
// result in compilation errors.
type UnsafeFoodServer interface {
	mustEmbedUnimplementedFoodServer()
}

func RegisterFoodServer(s grpc.ServiceRegistrar, srv FoodServer) {
	// If the following call pancis, it indicates UnimplementedFoodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Food_ServiceDesc, srv)
}

func _Food_CreateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).CreateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_CreateFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).CreateFood(ctx, req.(*CreateFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Food_GetFoodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFoodListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).GetFoodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_GetFoodList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).GetFoodList(ctx, req.(*GetFoodListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Food_GetRandomFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).GetRandomFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_GetRandomFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).GetRandomFood(ctx, req.(*GetRandomFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Food_ServiceDesc is the grpc.ServiceDesc for Food service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Food_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.v1.Food",
	HandlerType: (*FoodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFood",
			Handler:    _Food_CreateFood_Handler,
		},
		{
			MethodName: "GetFoodList",
			Handler:    _Food_GetFoodList_Handler,
		},
		{
			MethodName: "GetRandomFood",
			Handler:    _Food_GetRandomFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/food/v1/food.proto",
}
