// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/food/v1/food.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FoodMessage 食物信息
type FoodMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	View          []string               `protobuf:"bytes,2,rep,name=view,proto3" json:"view,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Describe      string                 `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	Recipe        string                 `protobuf:"bytes,5,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Article       string                 `protobuf:"bytes,6,opt,name=article,proto3" json:"article,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodMessage) Reset() {
	*x = FoodMessage{}
	mi := &file_api_food_v1_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodMessage) ProtoMessage() {}

func (x *FoodMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodMessage.ProtoReflect.Descriptor instead.
func (*FoodMessage) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{0}
}

func (x *FoodMessage) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *FoodMessage) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *FoodMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodMessage) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *FoodMessage) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

func (x *FoodMessage) GetArticle() string {
	if x != nil {
		return x.Article
	}
	return ""
}

func (x *FoodMessage) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FoodMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FoodMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateFoodRequest 创建食物请求
type CreateFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	View          []string               `protobuf:"bytes,2,rep,name=view,proto3" json:"view,omitempty"`
	Describe      string                 `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	Recipe        string                 `protobuf:"bytes,4,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Article       string                 `protobuf:"bytes,5,opt,name=article,proto3" json:"article,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFoodRequest) Reset() {
	*x = CreateFoodRequest{}
	mi := &file_api_food_v1_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodRequest) ProtoMessage() {}

func (x *CreateFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodRequest.ProtoReflect.Descriptor instead.
func (*CreateFoodRequest) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFoodRequest) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *CreateFoodRequest) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *CreateFoodRequest) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

func (x *CreateFoodRequest) GetArticle() string {
	if x != nil {
		return x.Article
	}
	return ""
}

func (x *CreateFoodRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// CreateFoodReply 创建食物响应
type CreateFoodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *FoodMessage           `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFoodReply) Reset() {
	*x = CreateFoodReply{}
	mi := &file_api_food_v1_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodReply) ProtoMessage() {}

func (x *CreateFoodReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodReply.ProtoReflect.Descriptor instead.
func (*CreateFoodReply) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFoodReply) GetFood() *FoodMessage {
	if x != nil {
		return x.Food
	}
	return nil
}

// GetFoodListRequest 获取食物列表请求
type GetFoodListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodListRequest) Reset() {
	*x = GetFoodListRequest{}
	mi := &file_api_food_v1_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodListRequest) ProtoMessage() {}

func (x *GetFoodListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodListRequest.ProtoReflect.Descriptor instead.
func (*GetFoodListRequest) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{3}
}

// GetFoodListReply 获取食物列表响应
type GetFoodListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foods         []*FoodMessage         `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodListReply) Reset() {
	*x = GetFoodListReply{}
	mi := &file_api_food_v1_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodListReply) ProtoMessage() {}

func (x *GetFoodListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodListReply.ProtoReflect.Descriptor instead.
func (*GetFoodListReply) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{4}
}

func (x *GetFoodListReply) GetFoods() []*FoodMessage {
	if x != nil {
		return x.Foods
	}
	return nil
}

// GetRandomFoodRequest 获取随机食物请求
type GetRandomFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFoodRequest) Reset() {
	*x = GetRandomFoodRequest{}
	mi := &file_api_food_v1_food_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFoodRequest) ProtoMessage() {}

func (x *GetRandomFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFoodRequest.ProtoReflect.Descriptor instead.
func (*GetRandomFoodRequest) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{5}
}

// GetRandomFoodReply 获取随机食物响应
type GetRandomFoodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *FoodMessage           `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFoodReply) Reset() {
	*x = GetRandomFoodReply{}
	mi := &file_api_food_v1_food_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFoodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFoodReply) ProtoMessage() {}

func (x *GetRandomFoodReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_food_v1_food_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFoodReply.ProtoReflect.Descriptor instead.
func (*GetRandomFoodReply) Descriptor() ([]byte, []int) {
	return file_api_food_v1_food_proto_rawDescGZIP(), []int{6}
}

func (x *GetRandomFoodReply) GetFood() *FoodMessage {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_api_food_v1_food_proto protoreflect.FileDescriptor

const file_api_food_v1_food_proto_rawDesc = "" +
	"\n" +
	"\x16api/food/v1/food.proto\x12\afood.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xef\x01\n" +
	"\vFoodMessage\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\x12\x12\n" +
	"\x04view\x18\x02 \x03(\tR\x04view\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\x12\x16\n" +
	"\x06recipe\x18\x05 \x01(\tR\x06recipe\x12\x18\n" +
	"\aarticle\x18\x06 \x01(\tR\aarticle\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xe2\x01\n" +
	"\x11CreateFoodRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x04name\x12\x1e\n" +
	"\x04view\x18\x02 \x03(\tB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x10\n" +
	"R\x04view\x12#\n" +
	"\bdescribe\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bdescribe\x12\x1f\n" +
	"\x06recipe\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06recipe\x12!\n" +
	"\aarticle\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aarticle\x12%\n" +
	"\blocation\x18\x06 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\x1eR\blocation\";\n" +
	"\x0fCreateFoodReply\x12(\n" +
	"\x04food\x18\x01 \x01(\v2\x14.food.v1.FoodMessageR\x04food\"\x14\n" +
	"\x12GetFoodListRequest\">\n" +
	"\x10GetFoodListReply\x12*\n" +
	"\x05foods\x18\x01 \x03(\v2\x14.food.v1.FoodMessageR\x05foods\"\x16\n" +
	"\x14GetRandomFoodRequest\">\n" +
	"\x12GetRandomFoodReply\x12(\n" +
	"\x04food\x18\x01 \x01(\v2\x14.food.v1.FoodMessageR\x04food2\x9e\x02\n" +
	"\x04Food\x12W\n" +
	"\n" +
	"CreateFood\x12\x1a.food.v1.CreateFoodRequest\x1a\x18.food.v1.CreateFoodReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/food\x12W\n" +
	"\vGetFoodList\x12\x1b.food.v1.GetFoodListRequest\x1a\x19.food.v1.GetFoodListReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/food\x12d\n" +
	"\rGetRandomFood\x12\x1d.food.v1.GetRandomFoodRequest\x1a\x1b.food.v1.GetRandomFoodReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/food/randomB\x15Z\x13food/api/food/v1;v1b\x06proto3"

var (
	file_api_food_v1_food_proto_rawDescOnce sync.Once
	file_api_food_v1_food_proto_rawDescData []byte
)

func file_api_food_v1_food_proto_rawDescGZIP() []byte {
	file_api_food_v1_food_proto_rawDescOnce.Do(func() {
		file_api_food_v1_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_food_v1_food_proto_rawDesc), len(file_api_food_v1_food_proto_rawDesc)))
	})
	return file_api_food_v1_food_proto_rawDescData
}

var file_api_food_v1_food_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_food_v1_food_proto_goTypes = []any{
	(*FoodMessage)(nil),          // 0: food.v1.FoodMessage
	(*CreateFoodRequest)(nil),    // 1: food.v1.CreateFoodRequest
	(*CreateFoodReply)(nil),      // 2: food.v1.CreateFoodReply
	(*GetFoodListRequest)(nil),   // 3: food.v1.GetFoodListRequest
	(*GetFoodListReply)(nil),     // 4: food.v1.GetFoodListReply
	(*GetRandomFoodRequest)(nil), // 5: food.v1.GetRandomFoodRequest
	(*GetRandomFoodReply)(nil),   // 6: food.v1.GetRandomFoodReply
}
var file_api_food_v1_food_proto_depIdxs = []int32{
	0, // 0: food.v1.CreateFoodReply.food:type_name -> food.v1.FoodMessage
	0, // 1: food.v1.GetFoodListReply.foods:type_name -> food.v1.FoodMessage
	0, // 2: food.v1.GetRandomFoodReply.food:type_name -> food.v1.FoodMessage
	1, // 3: food.v1.Food.CreateFood:input_type -> food.v1.CreateFoodRequest
	3, // 4: food.v1.Food.GetFoodList:input_type -> food.v1.GetFoodListRequest
	5, // 5: food.v1.Food.GetRandomFood:input_type -> food.v1.GetRandomFoodRequest
	2, // 6: food.v1.Food.CreateFood:output_type -> food.v1.CreateFoodReply
	4, // 7: food.v1.Food.GetFoodList:output_type -> food.v1.GetFoodListReply
	6, // 8: food.v1.Food.GetRandomFood:output_type -> food.v1.GetRandomFoodReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_food_v1_food_proto_init() }
func file_api_food_v1_food_proto_init() {
	if File_api_food_v1_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_food_v1_food_proto_rawDesc), len(file_api_food_v1_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_food_v1_food_proto_goTypes,
		DependencyIndexes: file_api_food_v1_food_proto_depIdxs,
		MessageInfos:      file_api_food_v1_food_proto_msgTypes,
	}.Build()
	File_api_food_v1_food_proto = out.File
	file_api_food_v1_food_proto_goTypes = nil
	file_api_food_v1_food_proto_depIdxs = nil
}
