// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.28.3
// source: api/food/v1/food.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFoodCreateFood = "/food.v1.Food/CreateFood"
const OperationFoodGetFoodList = "/food.v1.Food/GetFoodList"
const OperationFoodGetRandomFood = "/food.v1.Food/GetRandomFood"

type FoodHTTPServer interface {
	// CreateFood CreateFood 创建食物
	CreateFood(context.Context, *CreateFoodRequest) (*CreateFoodReply, error)
	// GetFoodList GetFoodList 获取食物列表
	GetFoodList(context.Context, *GetFoodListRequest) (*GetFoodListReply, error)
	// GetRandomFood GetRandomFood 获取随机食物
	GetRandomFood(context.Context, *GetRandomFoodRequest) (*GetRandomFoodReply, error)
}

func RegisterFoodHTTPServer(s *http.Server, srv FoodHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/food", _Food_CreateFood0_HTTP_Handler(srv))
	r.GET("/v1/food", _Food_GetFoodList0_HTTP_Handler(srv))
	r.GET("/v1/food/random", _Food_GetRandomFood0_HTTP_Handler(srv))
}

func _Food_CreateFood0_HTTP_Handler(srv FoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFoodRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFoodCreateFood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFood(ctx, req.(*CreateFoodRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateFoodReply)
		return ctx.Result(200, reply)
	}
}

func _Food_GetFoodList0_HTTP_Handler(srv FoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFoodListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFoodGetFoodList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFoodList(ctx, req.(*GetFoodListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetFoodListReply)
		return ctx.Result(200, reply)
	}
}

func _Food_GetRandomFood0_HTTP_Handler(srv FoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRandomFoodRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFoodGetRandomFood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRandomFood(ctx, req.(*GetRandomFoodRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRandomFoodReply)
		return ctx.Result(200, reply)
	}
}

type FoodHTTPClient interface {
	CreateFood(ctx context.Context, req *CreateFoodRequest, opts ...http.CallOption) (rsp *CreateFoodReply, err error)
	GetFoodList(ctx context.Context, req *GetFoodListRequest, opts ...http.CallOption) (rsp *GetFoodListReply, err error)
	GetRandomFood(ctx context.Context, req *GetRandomFoodRequest, opts ...http.CallOption) (rsp *GetRandomFoodReply, err error)
}

type FoodHTTPClientImpl struct {
	cc *http.Client
}

func NewFoodHTTPClient(client *http.Client) FoodHTTPClient {
	return &FoodHTTPClientImpl{client}
}

func (c *FoodHTTPClientImpl) CreateFood(ctx context.Context, in *CreateFoodRequest, opts ...http.CallOption) (*CreateFoodReply, error) {
	var out CreateFoodReply
	pattern := "/v1/food"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFoodCreateFood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FoodHTTPClientImpl) GetFoodList(ctx context.Context, in *GetFoodListRequest, opts ...http.CallOption) (*GetFoodListReply, error) {
	var out GetFoodListReply
	pattern := "/v1/food"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFoodGetFoodList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FoodHTTPClientImpl) GetRandomFood(ctx context.Context, in *GetRandomFoodRequest, opts ...http.CallOption) (*GetRandomFoodReply, error) {
	var out GetRandomFoodReply
	pattern := "/v1/food/random"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFoodGetRandomFood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
