// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.8
// source: api/audiobook/v1/audiobook.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Audiobook_CreateAudiobook_FullMethodName       = "/audiobook.v1.Audiobook/CreateAudiobook"
	Audiobook_CreateAudiobookDetail_FullMethodName = "/audiobook.v1.Audiobook/CreateAudiobookDetail"
	Audiobook_GetAudiobooks_FullMethodName         = "/audiobook.v1.Audiobook/GetAudiobooks"
	Audiobook_GetAudiobookDetails_FullMethodName   = "/audiobook.v1.Audiobook/GetAudiobookDetails"
)

// AudiobookClient is the client API for Audiobook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AudiobookService 有声书服务定义
type AudiobookClient interface {
	// CreateAudiobook 创建有声书
	CreateAudiobook(ctx context.Context, in *CreateAudiobookRequest, opts ...grpc.CallOption) (*CreateAudiobookReply, error)
	// CreateAudiobookDetail 创建有声书章节
	CreateAudiobookDetail(ctx context.Context, in *CreateAudiobookDetailRequest, opts ...grpc.CallOption) (*CreateAudiobookDetailReply, error)
	// GetAudiobooks 获取所有有声书
	GetAudiobooks(ctx context.Context, in *GetAudiobooksRequest, opts ...grpc.CallOption) (*GetAudiobooksReply, error)
	// GetAudiobookDetails 获取指定有声书的所有章节
	GetAudiobookDetails(ctx context.Context, in *GetAudiobookDetailsRequest, opts ...grpc.CallOption) (*GetAudiobookDetailsReply, error)
}

type audiobookClient struct {
	cc grpc.ClientConnInterface
}

func NewAudiobookClient(cc grpc.ClientConnInterface) AudiobookClient {
	return &audiobookClient{cc}
}

func (c *audiobookClient) CreateAudiobook(ctx context.Context, in *CreateAudiobookRequest, opts ...grpc.CallOption) (*CreateAudiobookReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAudiobookReply)
	err := c.cc.Invoke(ctx, Audiobook_CreateAudiobook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audiobookClient) CreateAudiobookDetail(ctx context.Context, in *CreateAudiobookDetailRequest, opts ...grpc.CallOption) (*CreateAudiobookDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAudiobookDetailReply)
	err := c.cc.Invoke(ctx, Audiobook_CreateAudiobookDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audiobookClient) GetAudiobooks(ctx context.Context, in *GetAudiobooksRequest, opts ...grpc.CallOption) (*GetAudiobooksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudiobooksReply)
	err := c.cc.Invoke(ctx, Audiobook_GetAudiobooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audiobookClient) GetAudiobookDetails(ctx context.Context, in *GetAudiobookDetailsRequest, opts ...grpc.CallOption) (*GetAudiobookDetailsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudiobookDetailsReply)
	err := c.cc.Invoke(ctx, Audiobook_GetAudiobookDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudiobookServer is the server API for Audiobook service.
// All implementations must embed UnimplementedAudiobookServer
// for forward compatibility.
//
// AudiobookService 有声书服务定义
type AudiobookServer interface {
	// CreateAudiobook 创建有声书
	CreateAudiobook(context.Context, *CreateAudiobookRequest) (*CreateAudiobookReply, error)
	// CreateAudiobookDetail 创建有声书章节
	CreateAudiobookDetail(context.Context, *CreateAudiobookDetailRequest) (*CreateAudiobookDetailReply, error)
	// GetAudiobooks 获取所有有声书
	GetAudiobooks(context.Context, *GetAudiobooksRequest) (*GetAudiobooksReply, error)
	// GetAudiobookDetails 获取指定有声书的所有章节
	GetAudiobookDetails(context.Context, *GetAudiobookDetailsRequest) (*GetAudiobookDetailsReply, error)
	mustEmbedUnimplementedAudiobookServer()
}

// UnimplementedAudiobookServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudiobookServer struct{}

func (UnimplementedAudiobookServer) CreateAudiobook(context.Context, *CreateAudiobookRequest) (*CreateAudiobookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAudiobook not implemented")
}
func (UnimplementedAudiobookServer) CreateAudiobookDetail(context.Context, *CreateAudiobookDetailRequest) (*CreateAudiobookDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAudiobookDetail not implemented")
}
func (UnimplementedAudiobookServer) GetAudiobooks(context.Context, *GetAudiobooksRequest) (*GetAudiobooksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudiobooks not implemented")
}
func (UnimplementedAudiobookServer) GetAudiobookDetails(context.Context, *GetAudiobookDetailsRequest) (*GetAudiobookDetailsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudiobookDetails not implemented")
}
func (UnimplementedAudiobookServer) mustEmbedUnimplementedAudiobookServer() {}
func (UnimplementedAudiobookServer) testEmbeddedByValue()                   {}

// UnsafeAudiobookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudiobookServer will
// result in compilation errors.
type UnsafeAudiobookServer interface {
	mustEmbedUnimplementedAudiobookServer()
}

func RegisterAudiobookServer(s grpc.ServiceRegistrar, srv AudiobookServer) {
	// If the following call pancis, it indicates UnimplementedAudiobookServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Audiobook_ServiceDesc, srv)
}

func _Audiobook_CreateAudiobook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAudiobookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudiobookServer).CreateAudiobook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audiobook_CreateAudiobook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudiobookServer).CreateAudiobook(ctx, req.(*CreateAudiobookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audiobook_CreateAudiobookDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAudiobookDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudiobookServer).CreateAudiobookDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audiobook_CreateAudiobookDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudiobookServer).CreateAudiobookDetail(ctx, req.(*CreateAudiobookDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audiobook_GetAudiobooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudiobooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudiobookServer).GetAudiobooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audiobook_GetAudiobooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudiobookServer).GetAudiobooks(ctx, req.(*GetAudiobooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audiobook_GetAudiobookDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudiobookDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudiobookServer).GetAudiobookDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Audiobook_GetAudiobookDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudiobookServer).GetAudiobookDetails(ctx, req.(*GetAudiobookDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Audiobook_ServiceDesc is the grpc.ServiceDesc for Audiobook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Audiobook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiobook.v1.Audiobook",
	HandlerType: (*AudiobookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAudiobook",
			Handler:    _Audiobook_CreateAudiobook_Handler,
		},
		{
			MethodName: "CreateAudiobookDetail",
			Handler:    _Audiobook_CreateAudiobookDetail_Handler,
		},
		{
			MethodName: "GetAudiobooks",
			Handler:    _Audiobook_GetAudiobooks_Handler,
		},
		{
			MethodName: "GetAudiobookDetails",
			Handler:    _Audiobook_GetAudiobookDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/audiobook/v1/audiobook.proto",
}
