// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.8
// source: api/audiobook/v1/audiobook.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudiobookMessage 有声书信息
type AudiobookMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	View          string                 `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Playcount     int32                  `protobuf:"varint,5,opt,name=playcount,proto3" json:"playcount,omitempty"`
	Chapternum    int32                  `protobuf:"varint,6,opt,name=chapternum,proto3" json:"chapternum,omitempty"`
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiobookMessage) Reset() {
	*x = AudiobookMessage{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiobookMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiobookMessage) ProtoMessage() {}

func (x *AudiobookMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiobookMessage.ProtoReflect.Descriptor instead.
func (*AudiobookMessage) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{0}
}

func (x *AudiobookMessage) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *AudiobookMessage) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *AudiobookMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AudiobookMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudiobookMessage) GetPlaycount() int32 {
	if x != nil {
		return x.Playcount
	}
	return 0
}

func (x *AudiobookMessage) GetChapternum() int32 {
	if x != nil {
		return x.Chapternum
	}
	return 0
}

func (x *AudiobookMessage) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AudiobookMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AudiobookMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AudiobookMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// AudiobookDetailMessage 有声书章节信息
type AudiobookDetailMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Bid           string                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Audio         string                 `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiobookDetailMessage) Reset() {
	*x = AudiobookDetailMessage{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiobookDetailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiobookDetailMessage) ProtoMessage() {}

func (x *AudiobookDetailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiobookDetailMessage.ProtoReflect.Descriptor instead.
func (*AudiobookDetailMessage) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{1}
}

func (x *AudiobookDetailMessage) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *AudiobookDetailMessage) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *AudiobookDetailMessage) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *AudiobookDetailMessage) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *AudiobookDetailMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudiobookDetailMessage) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AudiobookDetailMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AudiobookDetailMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateAudiobookRequest 创建有声书请求
type CreateAudiobookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudiobookRequest) Reset() {
	*x = CreateAudiobookRequest{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudiobookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudiobookRequest) ProtoMessage() {}

func (x *CreateAudiobookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudiobookRequest.ProtoReflect.Descriptor instead.
func (*CreateAudiobookRequest) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAudiobookRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *CreateAudiobookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateAudiobookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAudiobookRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateAudiobookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreateAudiobookReply 创建有声书响应
type CreateAudiobookReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audiobook     *AudiobookMessage      `protobuf:"bytes,1,opt,name=audiobook,proto3" json:"audiobook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudiobookReply) Reset() {
	*x = CreateAudiobookReply{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudiobookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudiobookReply) ProtoMessage() {}

func (x *CreateAudiobookReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudiobookReply.ProtoReflect.Descriptor instead.
func (*CreateAudiobookReply) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAudiobookReply) GetAudiobook() *AudiobookMessage {
	if x != nil {
		return x.Audiobook
	}
	return nil
}

// CreateAudiobookDetailRequest 创建有声书章节请求
type CreateAudiobookDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Chapter       int32                  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Audio         string                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudiobookDetailRequest) Reset() {
	*x = CreateAudiobookDetailRequest{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudiobookDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudiobookDetailRequest) ProtoMessage() {}

func (x *CreateAudiobookDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudiobookDetailRequest.ProtoReflect.Descriptor instead.
func (*CreateAudiobookDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAudiobookDetailRequest) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *CreateAudiobookDetailRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *CreateAudiobookDetailRequest) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *CreateAudiobookDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAudiobookDetailRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// CreateAudiobookDetailReply 创建有声书章节响应
type CreateAudiobookDetailReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Detail        *AudiobookDetailMessage `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudiobookDetailReply) Reset() {
	*x = CreateAudiobookDetailReply{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudiobookDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudiobookDetailReply) ProtoMessage() {}

func (x *CreateAudiobookDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudiobookDetailReply.ProtoReflect.Descriptor instead.
func (*CreateAudiobookDetailReply) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAudiobookDetailReply) GetDetail() *AudiobookDetailMessage {
	if x != nil {
		return x.Detail
	}
	return nil
}

// GetAudiobooksRequest 获取所有有声书请求
type GetAudiobooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudiobooksRequest) Reset() {
	*x = GetAudiobooksRequest{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudiobooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudiobooksRequest) ProtoMessage() {}

func (x *GetAudiobooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudiobooksRequest.ProtoReflect.Descriptor instead.
func (*GetAudiobooksRequest) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{6}
}

func (x *GetAudiobooksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetAudiobooksReply 获取所有有声书响应
type GetAudiobooksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audiobooks    []*AudiobookMessage    `protobuf:"bytes,1,rep,name=audiobooks,proto3" json:"audiobooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudiobooksReply) Reset() {
	*x = GetAudiobooksReply{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudiobooksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudiobooksReply) ProtoMessage() {}

func (x *GetAudiobooksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudiobooksReply.ProtoReflect.Descriptor instead.
func (*GetAudiobooksReply) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{7}
}

func (x *GetAudiobooksReply) GetAudiobooks() []*AudiobookMessage {
	if x != nil {
		return x.Audiobooks
	}
	return nil
}

// GetAudiobookDetailsRequest 获取指定有声书的所有章节请求
type GetAudiobookDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudiobookDetailsRequest) Reset() {
	*x = GetAudiobookDetailsRequest{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudiobookDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudiobookDetailsRequest) ProtoMessage() {}

func (x *GetAudiobookDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudiobookDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAudiobookDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{8}
}

func (x *GetAudiobookDetailsRequest) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

// GetAudiobookDetailsReply 获取指定有声书的所有章节响应
type GetAudiobookDetailsReply struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Details       []*AudiobookDetailMessage `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudiobookDetailsReply) Reset() {
	*x = GetAudiobookDetailsReply{}
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudiobookDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudiobookDetailsReply) ProtoMessage() {}

func (x *GetAudiobookDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_audiobook_v1_audiobook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudiobookDetailsReply.ProtoReflect.Descriptor instead.
func (*GetAudiobookDetailsReply) Descriptor() ([]byte, []int) {
	return file_api_audiobook_v1_audiobook_proto_rawDescGZIP(), []int{9}
}

func (x *GetAudiobookDetailsReply) GetDetails() []*AudiobookDetailMessage {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_audiobook_v1_audiobook_proto protoreflect.FileDescriptor

const file_api_audiobook_v1_audiobook_proto_rawDesc = "" +
	"\n" +
	" api/audiobook/v1/audiobook.proto\x12\faudiobook.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x9a\x02\n" +
	"\x10AudiobookMessage\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x12\n" +
	"\x04view\x18\x02 \x01(\tR\x04view\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tplaycount\x18\x05 \x01(\x05R\tplaycount\x12\x1e\n" +
	"\n" +
	"chapternum\x18\x06 \x01(\x05R\n" +
	"chapternum\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xda\x01\n" +
	"\x16AudiobookDetailMessage\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\tR\x03bid\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\x12\x14\n" +
	"\x05audio\x18\x04 \x01(\tR\x05audio\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xa8\x01\n" +
	"\x16CreateAudiobookRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12!\n" +
	"\x06author\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x06author\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x04name\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"T\n" +
	"\x14CreateAudiobookReply\x12<\n" +
	"\taudiobook\x18\x01 \x01(\v2\x1e.audiobook.v1.AudiobookMessageR\taudiobook\"\xae\x01\n" +
	"\x1cCreateAudiobookDetailRequest\x12\x19\n" +
	"\x03bid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03bid\x12\x18\n" +
	"\achapter\x18\x02 \x01(\x05R\achapter\x12\x1d\n" +
	"\x05audio\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05audio\x12\x1e\n" +
	"\x04name\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\"Z\n" +
	"\x1aCreateAudiobookDetailReply\x12<\n" +
	"\x06detail\x18\x01 \x01(\v2$.audiobook.v1.AudiobookDetailMessageR\x06detail\".\n" +
	"\x14GetAudiobooksRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\x12GetAudiobooksReply\x12>\n" +
	"\n" +
	"audiobooks\x18\x01 \x03(\v2\x1e.audiobook.v1.AudiobookMessageR\n" +
	"audiobooks\"7\n" +
	"\x1aGetAudiobookDetailsRequest\x12\x19\n" +
	"\x03bid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03bid\"Z\n" +
	"\x18GetAudiobookDetailsReply\x12>\n" +
	"\adetails\x18\x01 \x03(\v2$.audiobook.v1.AudiobookDetailMessageR\adetails2\x89\x04\n" +
	"\tAudiobook\x12u\n" +
	"\x0fCreateAudiobook\x12$.audiobook.v1.CreateAudiobookRequest\x1a\".audiobook.v1.CreateAudiobookReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/audiobook\x12\x8e\x01\n" +
	"\x15CreateAudiobookDetail\x12*.audiobook.v1.CreateAudiobookDetailRequest\x1a(.audiobook.v1.CreateAudiobookDetailReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/audiobook/detail\x12l\n" +
	"\rGetAudiobooks\x12\".audiobook.v1.GetAudiobooksRequest\x1a .audiobook.v1.GetAudiobooksReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/audiobook\x12\x85\x01\n" +
	"\x13GetAudiobookDetails\x12(.audiobook.v1.GetAudiobookDetailsRequest\x1a&.audiobook.v1.GetAudiobookDetailsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/audiobook/detailB\x1fZ\x1daudiobook/api/audiobook/v1;v1b\x06proto3"

var (
	file_api_audiobook_v1_audiobook_proto_rawDescOnce sync.Once
	file_api_audiobook_v1_audiobook_proto_rawDescData []byte
)

func file_api_audiobook_v1_audiobook_proto_rawDescGZIP() []byte {
	file_api_audiobook_v1_audiobook_proto_rawDescOnce.Do(func() {
		file_api_audiobook_v1_audiobook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_audiobook_v1_audiobook_proto_rawDesc), len(file_api_audiobook_v1_audiobook_proto_rawDesc)))
	})
	return file_api_audiobook_v1_audiobook_proto_rawDescData
}

var file_api_audiobook_v1_audiobook_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_audiobook_v1_audiobook_proto_goTypes = []any{
	(*AudiobookMessage)(nil),             // 0: audiobook.v1.AudiobookMessage
	(*AudiobookDetailMessage)(nil),       // 1: audiobook.v1.AudiobookDetailMessage
	(*CreateAudiobookRequest)(nil),       // 2: audiobook.v1.CreateAudiobookRequest
	(*CreateAudiobookReply)(nil),         // 3: audiobook.v1.CreateAudiobookReply
	(*CreateAudiobookDetailRequest)(nil), // 4: audiobook.v1.CreateAudiobookDetailRequest
	(*CreateAudiobookDetailReply)(nil),   // 5: audiobook.v1.CreateAudiobookDetailReply
	(*GetAudiobooksRequest)(nil),         // 6: audiobook.v1.GetAudiobooksRequest
	(*GetAudiobooksReply)(nil),           // 7: audiobook.v1.GetAudiobooksReply
	(*GetAudiobookDetailsRequest)(nil),   // 8: audiobook.v1.GetAudiobookDetailsRequest
	(*GetAudiobookDetailsReply)(nil),     // 9: audiobook.v1.GetAudiobookDetailsReply
}
var file_api_audiobook_v1_audiobook_proto_depIdxs = []int32{
	0, // 0: audiobook.v1.CreateAudiobookReply.audiobook:type_name -> audiobook.v1.AudiobookMessage
	1, // 1: audiobook.v1.CreateAudiobookDetailReply.detail:type_name -> audiobook.v1.AudiobookDetailMessage
	0, // 2: audiobook.v1.GetAudiobooksReply.audiobooks:type_name -> audiobook.v1.AudiobookMessage
	1, // 3: audiobook.v1.GetAudiobookDetailsReply.details:type_name -> audiobook.v1.AudiobookDetailMessage
	2, // 4: audiobook.v1.Audiobook.CreateAudiobook:input_type -> audiobook.v1.CreateAudiobookRequest
	4, // 5: audiobook.v1.Audiobook.CreateAudiobookDetail:input_type -> audiobook.v1.CreateAudiobookDetailRequest
	6, // 6: audiobook.v1.Audiobook.GetAudiobooks:input_type -> audiobook.v1.GetAudiobooksRequest
	8, // 7: audiobook.v1.Audiobook.GetAudiobookDetails:input_type -> audiobook.v1.GetAudiobookDetailsRequest
	3, // 8: audiobook.v1.Audiobook.CreateAudiobook:output_type -> audiobook.v1.CreateAudiobookReply
	5, // 9: audiobook.v1.Audiobook.CreateAudiobookDetail:output_type -> audiobook.v1.CreateAudiobookDetailReply
	7, // 10: audiobook.v1.Audiobook.GetAudiobooks:output_type -> audiobook.v1.GetAudiobooksReply
	9, // 11: audiobook.v1.Audiobook.GetAudiobookDetails:output_type -> audiobook.v1.GetAudiobookDetailsReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_audiobook_v1_audiobook_proto_init() }
func file_api_audiobook_v1_audiobook_proto_init() {
	if File_api_audiobook_v1_audiobook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_audiobook_v1_audiobook_proto_rawDesc), len(file_api_audiobook_v1_audiobook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_audiobook_v1_audiobook_proto_goTypes,
		DependencyIndexes: file_api_audiobook_v1_audiobook_proto_depIdxs,
		MessageInfos:      file_api_audiobook_v1_audiobook_proto_msgTypes,
	}.Build()
	File_api_audiobook_v1_audiobook_proto = out.File
	file_api_audiobook_v1_audiobook_proto_goTypes = nil
	file_api_audiobook_v1_audiobook_proto_depIdxs = nil
}
