// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/audiobook/v1/audiobook.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AudiobookMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AudiobookMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AudiobookMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AudiobookMessageMultiError, or nil if none found.
func (m *AudiobookMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *AudiobookMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Bid

	// no validation rules for View

	// no validation rules for Author

	// no validation rules for Name

	// no validation rules for Playcount

	// no validation rules for Chapternum

	// no validation rules for Rating

	// no validation rules for Description

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return AudiobookMessageMultiError(errors)
	}

	return nil
}

// AudiobookMessageMultiError is an error wrapping multiple validation errors
// returned by AudiobookMessage.ValidateAll() if the designated constraints
// aren't met.
type AudiobookMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AudiobookMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AudiobookMessageMultiError) AllErrors() []error { return m }

// AudiobookMessageValidationError is the validation error returned by
// AudiobookMessage.Validate if the designated constraints aren't met.
type AudiobookMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AudiobookMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AudiobookMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AudiobookMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AudiobookMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AudiobookMessageValidationError) ErrorName() string { return "AudiobookMessageValidationError" }

// Error satisfies the builtin error interface
func (e AudiobookMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAudiobookMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AudiobookMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AudiobookMessageValidationError{}

// Validate checks the field values on AudiobookDetailMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AudiobookDetailMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AudiobookDetailMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AudiobookDetailMessageMultiError, or nil if none found.
func (m *AudiobookDetailMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *AudiobookDetailMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Did

	// no validation rules for Bid

	// no validation rules for Chapter

	// no validation rules for Audio

	// no validation rules for Name

	// no validation rules for Duration

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return AudiobookDetailMessageMultiError(errors)
	}

	return nil
}

// AudiobookDetailMessageMultiError is an error wrapping multiple validation
// errors returned by AudiobookDetailMessage.ValidateAll() if the designated
// constraints aren't met.
type AudiobookDetailMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AudiobookDetailMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AudiobookDetailMessageMultiError) AllErrors() []error { return m }

// AudiobookDetailMessageValidationError is the validation error returned by
// AudiobookDetailMessage.Validate if the designated constraints aren't met.
type AudiobookDetailMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AudiobookDetailMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AudiobookDetailMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AudiobookDetailMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AudiobookDetailMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AudiobookDetailMessageValidationError) ErrorName() string {
	return "AudiobookDetailMessageValidationError"
}

// Error satisfies the builtin error interface
func (e AudiobookDetailMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAudiobookDetailMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AudiobookDetailMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AudiobookDetailMessageValidationError{}

// Validate checks the field values on CreateAudiobookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAudiobookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAudiobookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAudiobookRequestMultiError, or nil if none found.
func (m *CreateAudiobookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAudiobookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for View

	if l := utf8.RuneCountInString(m.GetAuthor()); l < 1 || l > 50 {
		err := CreateAudiobookRequestValidationError{
			field:  "Author",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 50 {
		err := CreateAudiobookRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Rating

	// no validation rules for Description

	if len(errors) > 0 {
		return CreateAudiobookRequestMultiError(errors)
	}

	return nil
}

// CreateAudiobookRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAudiobookRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAudiobookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAudiobookRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAudiobookRequestMultiError) AllErrors() []error { return m }

// CreateAudiobookRequestValidationError is the validation error returned by
// CreateAudiobookRequest.Validate if the designated constraints aren't met.
type CreateAudiobookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAudiobookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAudiobookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAudiobookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAudiobookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAudiobookRequestValidationError) ErrorName() string {
	return "CreateAudiobookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAudiobookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAudiobookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAudiobookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAudiobookRequestValidationError{}

// Validate checks the field values on CreateAudiobookReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAudiobookReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAudiobookReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAudiobookReplyMultiError, or nil if none found.
func (m *CreateAudiobookReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAudiobookReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAudiobook()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateAudiobookReplyValidationError{
					field:  "Audiobook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateAudiobookReplyValidationError{
					field:  "Audiobook",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAudiobook()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateAudiobookReplyValidationError{
				field:  "Audiobook",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateAudiobookReplyMultiError(errors)
	}

	return nil
}

// CreateAudiobookReplyMultiError is an error wrapping multiple validation
// errors returned by CreateAudiobookReply.ValidateAll() if the designated
// constraints aren't met.
type CreateAudiobookReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAudiobookReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAudiobookReplyMultiError) AllErrors() []error { return m }

// CreateAudiobookReplyValidationError is the validation error returned by
// CreateAudiobookReply.Validate if the designated constraints aren't met.
type CreateAudiobookReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAudiobookReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAudiobookReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAudiobookReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAudiobookReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAudiobookReplyValidationError) ErrorName() string {
	return "CreateAudiobookReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAudiobookReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAudiobookReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAudiobookReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAudiobookReplyValidationError{}

// Validate checks the field values on CreateAudiobookDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAudiobookDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAudiobookDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAudiobookDetailRequestMultiError, or nil if none found.
func (m *CreateAudiobookDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAudiobookDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBid()) < 1 {
		err := CreateAudiobookDetailRequestValidationError{
			field:  "Bid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Chapter

	if utf8.RuneCountInString(m.GetAudio()) < 1 {
		err := CreateAudiobookDetailRequestValidationError{
			field:  "Audio",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 255 {
		err := CreateAudiobookDetailRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Duration

	if len(errors) > 0 {
		return CreateAudiobookDetailRequestMultiError(errors)
	}

	return nil
}

// CreateAudiobookDetailRequestMultiError is an error wrapping multiple
// validation errors returned by CreateAudiobookDetailRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateAudiobookDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAudiobookDetailRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAudiobookDetailRequestMultiError) AllErrors() []error { return m }

// CreateAudiobookDetailRequestValidationError is the validation error returned
// by CreateAudiobookDetailRequest.Validate if the designated constraints
// aren't met.
type CreateAudiobookDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAudiobookDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAudiobookDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAudiobookDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAudiobookDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAudiobookDetailRequestValidationError) ErrorName() string {
	return "CreateAudiobookDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAudiobookDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAudiobookDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAudiobookDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAudiobookDetailRequestValidationError{}

// Validate checks the field values on CreateAudiobookDetailReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAudiobookDetailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAudiobookDetailReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAudiobookDetailReplyMultiError, or nil if none found.
func (m *CreateAudiobookDetailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAudiobookDetailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateAudiobookDetailReplyValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateAudiobookDetailReplyValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateAudiobookDetailReplyValidationError{
				field:  "Detail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateAudiobookDetailReplyMultiError(errors)
	}

	return nil
}

// CreateAudiobookDetailReplyMultiError is an error wrapping multiple
// validation errors returned by CreateAudiobookDetailReply.ValidateAll() if
// the designated constraints aren't met.
type CreateAudiobookDetailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAudiobookDetailReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAudiobookDetailReplyMultiError) AllErrors() []error { return m }

// CreateAudiobookDetailReplyValidationError is the validation error returned
// by CreateAudiobookDetailReply.Validate if the designated constraints aren't met.
type CreateAudiobookDetailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAudiobookDetailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAudiobookDetailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAudiobookDetailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAudiobookDetailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAudiobookDetailReplyValidationError) ErrorName() string {
	return "CreateAudiobookDetailReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAudiobookDetailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAudiobookDetailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAudiobookDetailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAudiobookDetailReplyValidationError{}

// Validate checks the field values on GetAudiobooksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAudiobooksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAudiobooksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAudiobooksRequestMultiError, or nil if none found.
func (m *GetAudiobooksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAudiobooksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return GetAudiobooksRequestMultiError(errors)
	}

	return nil
}

// GetAudiobooksRequestMultiError is an error wrapping multiple validation
// errors returned by GetAudiobooksRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAudiobooksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAudiobooksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAudiobooksRequestMultiError) AllErrors() []error { return m }

// GetAudiobooksRequestValidationError is the validation error returned by
// GetAudiobooksRequest.Validate if the designated constraints aren't met.
type GetAudiobooksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAudiobooksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAudiobooksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAudiobooksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAudiobooksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAudiobooksRequestValidationError) ErrorName() string {
	return "GetAudiobooksRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAudiobooksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAudiobooksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAudiobooksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAudiobooksRequestValidationError{}

// Validate checks the field values on GetAudiobooksReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAudiobooksReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAudiobooksReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAudiobooksReplyMultiError, or nil if none found.
func (m *GetAudiobooksReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAudiobooksReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAudiobooks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAudiobooksReplyValidationError{
						field:  fmt.Sprintf("Audiobooks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAudiobooksReplyValidationError{
						field:  fmt.Sprintf("Audiobooks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAudiobooksReplyValidationError{
					field:  fmt.Sprintf("Audiobooks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAudiobooksReplyMultiError(errors)
	}

	return nil
}

// GetAudiobooksReplyMultiError is an error wrapping multiple validation errors
// returned by GetAudiobooksReply.ValidateAll() if the designated constraints
// aren't met.
type GetAudiobooksReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAudiobooksReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAudiobooksReplyMultiError) AllErrors() []error { return m }

// GetAudiobooksReplyValidationError is the validation error returned by
// GetAudiobooksReply.Validate if the designated constraints aren't met.
type GetAudiobooksReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAudiobooksReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAudiobooksReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAudiobooksReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAudiobooksReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAudiobooksReplyValidationError) ErrorName() string {
	return "GetAudiobooksReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAudiobooksReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAudiobooksReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAudiobooksReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAudiobooksReplyValidationError{}

// Validate checks the field values on GetAudiobookDetailsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAudiobookDetailsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAudiobookDetailsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAudiobookDetailsRequestMultiError, or nil if none found.
func (m *GetAudiobookDetailsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAudiobookDetailsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBid()) < 1 {
		err := GetAudiobookDetailsRequestValidationError{
			field:  "Bid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetAudiobookDetailsRequestMultiError(errors)
	}

	return nil
}

// GetAudiobookDetailsRequestMultiError is an error wrapping multiple
// validation errors returned by GetAudiobookDetailsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetAudiobookDetailsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAudiobookDetailsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAudiobookDetailsRequestMultiError) AllErrors() []error { return m }

// GetAudiobookDetailsRequestValidationError is the validation error returned
// by GetAudiobookDetailsRequest.Validate if the designated constraints aren't met.
type GetAudiobookDetailsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAudiobookDetailsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAudiobookDetailsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAudiobookDetailsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAudiobookDetailsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAudiobookDetailsRequestValidationError) ErrorName() string {
	return "GetAudiobookDetailsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAudiobookDetailsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAudiobookDetailsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAudiobookDetailsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAudiobookDetailsRequestValidationError{}

// Validate checks the field values on GetAudiobookDetailsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAudiobookDetailsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAudiobookDetailsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAudiobookDetailsReplyMultiError, or nil if none found.
func (m *GetAudiobookDetailsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAudiobookDetailsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDetails() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAudiobookDetailsReplyValidationError{
						field:  fmt.Sprintf("Details[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAudiobookDetailsReplyValidationError{
						field:  fmt.Sprintf("Details[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAudiobookDetailsReplyValidationError{
					field:  fmt.Sprintf("Details[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAudiobookDetailsReplyMultiError(errors)
	}

	return nil
}

// GetAudiobookDetailsReplyMultiError is an error wrapping multiple validation
// errors returned by GetAudiobookDetailsReply.ValidateAll() if the designated
// constraints aren't met.
type GetAudiobookDetailsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAudiobookDetailsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAudiobookDetailsReplyMultiError) AllErrors() []error { return m }

// GetAudiobookDetailsReplyValidationError is the validation error returned by
// GetAudiobookDetailsReply.Validate if the designated constraints aren't met.
type GetAudiobookDetailsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAudiobookDetailsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAudiobookDetailsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAudiobookDetailsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAudiobookDetailsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAudiobookDetailsReplyValidationError) ErrorName() string {
	return "GetAudiobookDetailsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAudiobookDetailsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAudiobookDetailsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAudiobookDetailsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAudiobookDetailsReplyValidationError{}
