// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v4.25.8
// source: api/audiobook/v1/audiobook.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAudiobookCreateAudiobook = "/audiobook.v1.Audiobook/CreateAudiobook"
const OperationAudiobookCreateAudiobookDetail = "/audiobook.v1.Audiobook/CreateAudiobookDetail"
const OperationAudiobookGetAudiobookDetails = "/audiobook.v1.Audiobook/GetAudiobookDetails"
const OperationAudiobookGetAudiobooks = "/audiobook.v1.Audiobook/GetAudiobooks"

type AudiobookHTTPServer interface {
	// CreateAudiobook CreateAudiobook 创建有声书
	CreateAudiobook(context.Context, *CreateAudiobookRequest) (*CreateAudiobookReply, error)
	// CreateAudiobookDetail CreateAudiobookDetail 创建有声书章节
	CreateAudiobookDetail(context.Context, *CreateAudiobookDetailRequest) (*CreateAudiobookDetailReply, error)
	// GetAudiobookDetails GetAudiobookDetails 获取指定有声书的所有章节
	GetAudiobookDetails(context.Context, *GetAudiobookDetailsRequest) (*GetAudiobookDetailsReply, error)
	// GetAudiobooks GetAudiobooks 获取所有有声书
	GetAudiobooks(context.Context, *GetAudiobooksRequest) (*GetAudiobooksReply, error)
}

func RegisterAudiobookHTTPServer(s *http.Server, srv AudiobookHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/audiobook", _Audiobook_CreateAudiobook0_HTTP_Handler(srv))
	r.POST("/v1/audiobook/detail", _Audiobook_CreateAudiobookDetail0_HTTP_Handler(srv))
	r.GET("/v1/audiobook", _Audiobook_GetAudiobooks0_HTTP_Handler(srv))
	r.GET("/v1/audiobook/detail", _Audiobook_GetAudiobookDetails0_HTTP_Handler(srv))
}

func _Audiobook_CreateAudiobook0_HTTP_Handler(srv AudiobookHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAudiobookRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAudiobookCreateAudiobook)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAudiobook(ctx, req.(*CreateAudiobookRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAudiobookReply)
		return ctx.Result(200, reply)
	}
}

func _Audiobook_CreateAudiobookDetail0_HTTP_Handler(srv AudiobookHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAudiobookDetailRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAudiobookCreateAudiobookDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAudiobookDetail(ctx, req.(*CreateAudiobookDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAudiobookDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Audiobook_GetAudiobooks0_HTTP_Handler(srv AudiobookHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAudiobooksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAudiobookGetAudiobooks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAudiobooks(ctx, req.(*GetAudiobooksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAudiobooksReply)
		return ctx.Result(200, reply)
	}
}

func _Audiobook_GetAudiobookDetails0_HTTP_Handler(srv AudiobookHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAudiobookDetailsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAudiobookGetAudiobookDetails)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAudiobookDetails(ctx, req.(*GetAudiobookDetailsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAudiobookDetailsReply)
		return ctx.Result(200, reply)
	}
}

type AudiobookHTTPClient interface {
	CreateAudiobook(ctx context.Context, req *CreateAudiobookRequest, opts ...http.CallOption) (rsp *CreateAudiobookReply, err error)
	CreateAudiobookDetail(ctx context.Context, req *CreateAudiobookDetailRequest, opts ...http.CallOption) (rsp *CreateAudiobookDetailReply, err error)
	GetAudiobookDetails(ctx context.Context, req *GetAudiobookDetailsRequest, opts ...http.CallOption) (rsp *GetAudiobookDetailsReply, err error)
	GetAudiobooks(ctx context.Context, req *GetAudiobooksRequest, opts ...http.CallOption) (rsp *GetAudiobooksReply, err error)
}

type AudiobookHTTPClientImpl struct {
	cc *http.Client
}

func NewAudiobookHTTPClient(client *http.Client) AudiobookHTTPClient {
	return &AudiobookHTTPClientImpl{client}
}

func (c *AudiobookHTTPClientImpl) CreateAudiobook(ctx context.Context, in *CreateAudiobookRequest, opts ...http.CallOption) (*CreateAudiobookReply, error) {
	var out CreateAudiobookReply
	pattern := "/v1/audiobook"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAudiobookCreateAudiobook))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AudiobookHTTPClientImpl) CreateAudiobookDetail(ctx context.Context, in *CreateAudiobookDetailRequest, opts ...http.CallOption) (*CreateAudiobookDetailReply, error) {
	var out CreateAudiobookDetailReply
	pattern := "/v1/audiobook/detail"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAudiobookCreateAudiobookDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AudiobookHTTPClientImpl) GetAudiobookDetails(ctx context.Context, in *GetAudiobookDetailsRequest, opts ...http.CallOption) (*GetAudiobookDetailsReply, error) {
	var out GetAudiobookDetailsReply
	pattern := "/v1/audiobook/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAudiobookGetAudiobookDetails))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AudiobookHTTPClientImpl) GetAudiobooks(ctx context.Context, in *GetAudiobooksRequest, opts ...http.CallOption) (*GetAudiobooksReply, error) {
	var out GetAudiobooksReply
	pattern := "/v1/audiobook"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAudiobookGetAudiobooks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
