// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 未知错误
func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

// 未知错误
func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

// 有声书不存在
func IsAudiobookNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUDIOBOOK_NOT_FOUND.String() && e.Code == 404
}

// 有声书不存在
func ErrorAudiobookNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_AUDIOBOOK_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 章节不存在
func IsDetailNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DETAIL_NOT_FOUND.String() && e.Code == 404
}

// 章节不存在
func ErrorDetailNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_DETAIL_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 创建有声书失败
func IsCreateAudiobookFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CREATE_AUDIOBOOK_FAILED.String() && e.Code == 500
}

// 创建有声书失败
func ErrorCreateAudiobookFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CREATE_AUDIOBOOK_FAILED.String(), fmt.Sprintf(format, args...))
}

// 创建章节失败
func IsCreateDetailFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CREATE_DETAIL_FAILED.String() && e.Code == 500
}

// 创建章节失败
func ErrorCreateDetailFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CREATE_DETAIL_FAILED.String(), fmt.Sprintf(format, args...))
}

// 数据库错误
func IsDatabaseError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATABASE_ERROR.String() && e.Code == 500
}

// 数据库错误
func ErrorDatabaseError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DATABASE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 缓存错误
func IsCacheError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CACHE_ERROR.String() && e.Code == 500
}

// 缓存错误
func ErrorCacheError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CACHE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 参数错误
func IsInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ARGUMENT.String() && e.Code == 400
}

// 参数错误
func ErrorInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}
