// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/scene/v1/scene.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SceneMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SceneMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SceneMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SceneMessageMultiError, or
// nil if none found.
func (m *SceneMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *SceneMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sid

	// no validation rules for Name

	// no validation rules for Describe

	// no validation rules for Location

	// no validation rules for Article

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return SceneMessageMultiError(errors)
	}

	return nil
}

// SceneMessageMultiError is an error wrapping multiple validation errors
// returned by SceneMessage.ValidateAll() if the designated constraints aren't met.
type SceneMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SceneMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SceneMessageMultiError) AllErrors() []error { return m }

// SceneMessageValidationError is the validation error returned by
// SceneMessage.Validate if the designated constraints aren't met.
type SceneMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SceneMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SceneMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SceneMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SceneMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SceneMessageValidationError) ErrorName() string { return "SceneMessageValidationError" }

// Error satisfies the builtin error interface
func (e SceneMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSceneMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SceneMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SceneMessageValidationError{}

// Validate checks the field values on CreateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSceneRequestMultiError, or nil if none found.
func (m *CreateSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 2 || l > 100 {
		err := CreateSceneRequestValidationError{
			field:  "Name",
			reason: "value length must be between 2 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescribe()) > 400 {
		err := CreateSceneRequestValidationError{
			field:  "Describe",
			reason: "value length must be at most 400 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLocation()) > 20 {
		err := CreateSceneRequestValidationError{
			field:  "Location",
			reason: "value length must be at most 20 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Article

	if len(errors) > 0 {
		return CreateSceneRequestMultiError(errors)
	}

	return nil
}

// CreateSceneRequestMultiError is an error wrapping multiple validation errors
// returned by CreateSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSceneRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSceneRequestMultiError) AllErrors() []error { return m }

// CreateSceneRequestValidationError is the validation error returned by
// CreateSceneRequest.Validate if the designated constraints aren't met.
type CreateSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSceneRequestValidationError) ErrorName() string {
	return "CreateSceneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSceneRequestValidationError{}

// Validate checks the field values on CreateSceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateSceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSceneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSceneReplyMultiError, or nil if none found.
func (m *CreateSceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetScene()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateSceneReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateSceneReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetScene()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateSceneReplyValidationError{
				field:  "Scene",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateSceneReplyMultiError(errors)
	}

	return nil
}

// CreateSceneReplyMultiError is an error wrapping multiple validation errors
// returned by CreateSceneReply.ValidateAll() if the designated constraints
// aren't met.
type CreateSceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSceneReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSceneReplyMultiError) AllErrors() []error { return m }

// CreateSceneReplyValidationError is the validation error returned by
// CreateSceneReply.Validate if the designated constraints aren't met.
type CreateSceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSceneReplyValidationError) ErrorName() string { return "CreateSceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateSceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSceneReplyValidationError{}

// Validate checks the field values on DeleteSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSceneRequestMultiError, or nil if none found.
func (m *DeleteSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSid()) < 1 {
		err := DeleteSceneRequestValidationError{
			field:  "Sid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSceneRequestMultiError(errors)
	}

	return nil
}

// DeleteSceneRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSceneRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSceneRequestMultiError) AllErrors() []error { return m }

// DeleteSceneRequestValidationError is the validation error returned by
// DeleteSceneRequest.Validate if the designated constraints aren't met.
type DeleteSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSceneRequestValidationError) ErrorName() string {
	return "DeleteSceneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSceneRequestValidationError{}

// Validate checks the field values on DeleteSceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteSceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSceneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSceneReplyMultiError, or nil if none found.
func (m *DeleteSceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteSceneReplyMultiError(errors)
	}

	return nil
}

// DeleteSceneReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteSceneReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteSceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSceneReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSceneReplyMultiError) AllErrors() []error { return m }

// DeleteSceneReplyValidationError is the validation error returned by
// DeleteSceneReply.Validate if the designated constraints aren't met.
type DeleteSceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSceneReplyValidationError) ErrorName() string { return "DeleteSceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeleteSceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSceneReplyValidationError{}

// Validate checks the field values on UpdateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSceneRequestMultiError, or nil if none found.
func (m *UpdateSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSid()) < 1 {
		err := UpdateSceneRequestValidationError{
			field:  "Sid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Name

	// no validation rules for Describe

	// no validation rules for Location

	// no validation rules for Article

	if len(errors) > 0 {
		return UpdateSceneRequestMultiError(errors)
	}

	return nil
}

// UpdateSceneRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSceneRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSceneRequestMultiError) AllErrors() []error { return m }

// UpdateSceneRequestValidationError is the validation error returned by
// UpdateSceneRequest.Validate if the designated constraints aren't met.
type UpdateSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSceneRequestValidationError) ErrorName() string {
	return "UpdateSceneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSceneRequestValidationError{}

// Validate checks the field values on UpdateSceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateSceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSceneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSceneReplyMultiError, or nil if none found.
func (m *UpdateSceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetScene()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateSceneReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateSceneReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetScene()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateSceneReplyValidationError{
				field:  "Scene",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateSceneReplyMultiError(errors)
	}

	return nil
}

// UpdateSceneReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateSceneReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateSceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSceneReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSceneReplyMultiError) AllErrors() []error { return m }

// UpdateSceneReplyValidationError is the validation error returned by
// UpdateSceneReply.Validate if the designated constraints aren't met.
type UpdateSceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSceneReplyValidationError) ErrorName() string { return "UpdateSceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e UpdateSceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSceneReplyValidationError{}

// Validate checks the field values on SearchSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchSceneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchSceneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchSceneRequestMultiError, or nil if none found.
func (m *SearchSceneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchSceneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKeyword()) < 1 {
		err := SearchSceneRequestValidationError{
			field:  "Keyword",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPage() < 1 {
		err := SearchSceneRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPagesize() < 1 {
		err := SearchSceneRequestValidationError{
			field:  "Pagesize",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SearchSceneRequestMultiError(errors)
	}

	return nil
}

// SearchSceneRequestMultiError is an error wrapping multiple validation errors
// returned by SearchSceneRequest.ValidateAll() if the designated constraints
// aren't met.
type SearchSceneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchSceneRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchSceneRequestMultiError) AllErrors() []error { return m }

// SearchSceneRequestValidationError is the validation error returned by
// SearchSceneRequest.Validate if the designated constraints aren't met.
type SearchSceneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchSceneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchSceneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchSceneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchSceneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchSceneRequestValidationError) ErrorName() string {
	return "SearchSceneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchSceneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchSceneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchSceneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchSceneRequestValidationError{}

// Validate checks the field values on SearchSceneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SearchSceneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchSceneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchSceneReplyMultiError, or nil if none found.
func (m *SearchSceneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchSceneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetScenes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchSceneReplyValidationError{
						field:  fmt.Sprintf("Scenes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchSceneReplyValidationError{
						field:  fmt.Sprintf("Scenes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchSceneReplyValidationError{
					field:  fmt.Sprintf("Scenes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Hits

	if len(errors) > 0 {
		return SearchSceneReplyMultiError(errors)
	}

	return nil
}

// SearchSceneReplyMultiError is an error wrapping multiple validation errors
// returned by SearchSceneReply.ValidateAll() if the designated constraints
// aren't met.
type SearchSceneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchSceneReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchSceneReplyMultiError) AllErrors() []error { return m }

// SearchSceneReplyValidationError is the validation error returned by
// SearchSceneReply.Validate if the designated constraints aren't met.
type SearchSceneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchSceneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchSceneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchSceneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchSceneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchSceneReplyValidationError) ErrorName() string { return "SearchSceneReplyValidationError" }

// Error satisfies the builtin error interface
func (e SearchSceneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchSceneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchSceneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchSceneReplyValidationError{}

// Validate checks the field values on ListScenesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListScenesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListScenesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListScenesRequestMultiError, or nil if none found.
func (m *ListScenesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListScenesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() < 1 {
		err := ListScenesRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPagesize() < 1 {
		err := ListScenesRequestValidationError{
			field:  "Pagesize",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListScenesRequestMultiError(errors)
	}

	return nil
}

// ListScenesRequestMultiError is an error wrapping multiple validation errors
// returned by ListScenesRequest.ValidateAll() if the designated constraints
// aren't met.
type ListScenesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListScenesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListScenesRequestMultiError) AllErrors() []error { return m }

// ListScenesRequestValidationError is the validation error returned by
// ListScenesRequest.Validate if the designated constraints aren't met.
type ListScenesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListScenesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListScenesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListScenesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListScenesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListScenesRequestValidationError) ErrorName() string {
	return "ListScenesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListScenesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListScenesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListScenesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListScenesRequestValidationError{}

// Validate checks the field values on ListScenesReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListScenesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListScenesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListScenesReplyMultiError, or nil if none found.
func (m *ListScenesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListScenesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetScenes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListScenesReplyValidationError{
						field:  fmt.Sprintf("Scenes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListScenesReplyValidationError{
						field:  fmt.Sprintf("Scenes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListScenesReplyValidationError{
					field:  fmt.Sprintf("Scenes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListScenesReplyMultiError(errors)
	}

	return nil
}

// ListScenesReplyMultiError is an error wrapping multiple validation errors
// returned by ListScenesReply.ValidateAll() if the designated constraints
// aren't met.
type ListScenesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListScenesReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListScenesReplyMultiError) AllErrors() []error { return m }

// ListScenesReplyValidationError is the validation error returned by
// ListScenesReply.Validate if the designated constraints aren't met.
type ListScenesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListScenesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListScenesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListScenesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListScenesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListScenesReplyValidationError) ErrorName() string { return "ListScenesReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListScenesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListScenesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListScenesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListScenesReplyValidationError{}

// Validate checks the field values on GetSceneByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSceneByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSceneByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSceneByIDRequestMultiError, or nil if none found.
func (m *GetSceneByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSceneByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSid()) < 1 {
		err := GetSceneByIDRequestValidationError{
			field:  "Sid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSceneByIDRequestMultiError(errors)
	}

	return nil
}

// GetSceneByIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetSceneByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSceneByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSceneByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSceneByIDRequestMultiError) AllErrors() []error { return m }

// GetSceneByIDRequestValidationError is the validation error returned by
// GetSceneByIDRequest.Validate if the designated constraints aren't met.
type GetSceneByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSceneByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSceneByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSceneByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSceneByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSceneByIDRequestValidationError) ErrorName() string {
	return "GetSceneByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSceneByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSceneByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSceneByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSceneByIDRequestValidationError{}

// Validate checks the field values on GetSceneByIDReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSceneByIDReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSceneByIDReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSceneByIDReplyMultiError, or nil if none found.
func (m *GetSceneByIDReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSceneByIDReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetScene()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSceneByIDReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSceneByIDReplyValidationError{
					field:  "Scene",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetScene()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSceneByIDReplyValidationError{
				field:  "Scene",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSceneByIDReplyMultiError(errors)
	}

	return nil
}

// GetSceneByIDReplyMultiError is an error wrapping multiple validation errors
// returned by GetSceneByIDReply.ValidateAll() if the designated constraints
// aren't met.
type GetSceneByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSceneByIDReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSceneByIDReplyMultiError) AllErrors() []error { return m }

// GetSceneByIDReplyValidationError is the validation error returned by
// GetSceneByIDReply.Validate if the designated constraints aren't met.
type GetSceneByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSceneByIDReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSceneByIDReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSceneByIDReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSceneByIDReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSceneByIDReplyValidationError) ErrorName() string {
	return "GetSceneByIDReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSceneByIDReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSceneByIDReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSceneByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSceneByIDReplyValidationError{}
