// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/user/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_NOT_FOUND                 ErrorReason = 0
	ErrorReason_INVALID_ARGUMENT          ErrorReason = 1
	ErrorReason_EMAIL_ALREADY_EXISTS      ErrorReason = 2
	ErrorReason_USERNAME_ALREADY_EXISTS   ErrorReason = 3
	ErrorReason_VERIFICATION_CODE_EXPIRED ErrorReason = 4
	ErrorReason_INCORRECT_PASSWORD        ErrorReason = 5
	ErrorReason_UNAUTHORIZED              ErrorReason = 6
	ErrorReason_INTERNAL_ERROR            ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "NOT_FOUND",
		1: "INVALID_ARGUMENT",
		2: "EMAIL_ALREADY_EXISTS",
		3: "USERNAME_ALREADY_EXISTS",
		4: "VERIFICATION_CODE_EXPIRED",
		5: "INCORRECT_PASSWORD",
		6: "UNAUTHORIZED",
		7: "INTERNAL_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"NOT_FOUND":                 0,
		"INVALID_ARGUMENT":          1,
		"EMAIL_ALREADY_EXISTS":      2,
		"USERNAME_ALREADY_EXISTS":   3,
		"VERIFICATION_CODE_EXPIRED": 4,
		"INCORRECT_PASSWORD":        5,
		"UNAUTHORIZED":              6,
		"INTERNAL_ERROR":            7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_api_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_api_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/user/v1/error_reason.proto\x12\auser.v1\x1a\x13errors/errors.proto*\xfc\x01\n" +
	"\vErrorReason\x12\x13\n" +
	"\tNOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1a\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14EMAIL_ALREADY_EXISTS\x10\x02\x1a\x04\xa8E\x99\x03\x12!\n" +
	"\x17USERNAME_ALREADY_EXISTS\x10\x03\x1a\x04\xa8E\x99\x03\x12#\n" +
	"\x19VERIFICATION_CODE_EXPIRED\x10\x04\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12INCORRECT_PASSWORD\x10\x05\x1a\x04\xa8E\x91\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x06\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\x0eINTERNAL_ERROR\x10\a\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B\x15Z\x13user/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_api_user_v1_error_reason_proto_rawDescData []byte
)

func file_api_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_api_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_api_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_error_reason_proto_rawDesc), len(file_api_user_v1_error_reason_proto_rawDesc)))
	})
	return file_api_user_v1_error_reason_proto_rawDescData
}

var file_api_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: user.v1.ErrorReason
}
var file_api_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_v1_error_reason_proto_init() }
func file_api_user_v1_error_reason_proto_init() {
	if File_api_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_error_reason_proto_rawDesc), len(file_api_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_api_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_api_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_api_user_v1_error_reason_proto = out.File
	file_api_user_v1_error_reason_proto_goTypes = nil
	file_api_user_v1_error_reason_proto_depIdxs = nil
}
